config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root 'movies#index'
  resources :movies
  resources :genres, except: %i[destroy edit show index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movie_genres
  has_many :movies, through: :movie_genres
  validates :name, presence: true,
                   uniqueness: { case_sensitive: false },
                   length: { minimum: 2, maximum: 20 }
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :movie_genres
  has_many :genres, through: :movie_genres

  validates :title, presence: true,
                    length: { minimum: 3, maximum: 50 }

  validates :director, presence: true,
                       length: { minimum: 5, maximum: 300 }

  validates :release_year, presence: true
  validates :genre_ids, presence: true

  def most_watched?
    view_count == Movie.maximum(:view_count) && Movie.count > 1 && view_count != 0
  end

  def display_genres(movie)
    final_arr = []
    movie.genres.each do |genre|
      final_arr << genre.name
    end
    final_arr.join(', ')
  end

  def display_movie_director_realse_year(movie)
    "#{movie.title} by #{movie.director} (#{movie.release_year})"
  end
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = 'Genre was successfully created'
      redirect_to root_path
    else
      flash[:notice] = 'There was an error'
      render 'new'
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[edit update]

  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def edit; end

  def update
    if @movie.update(update_movie_params)
      flash[:notice] = "Movie '#{@movie.title}' views updated successfully!"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      flash[:notice] = "Movie '#{@movie.title}' has been added successfully!"
      redirect_to root_path
    else
      flash[:notice] = 'There was an error'
      render 'new'
    end
  end
end

private

def movie_params
  params.require(:movie).permit(:title, :director, :release_year, genre_ids: [])
end

def update_movie_params
  params.require(:movie).permit(:view_count)
end

def set_movie
  @movie = Movie.find(params[:id])
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/genres/new.html.erb
<h1>Create Genre</h1>
<%= form_with(model: @genre, local: true, data: { turbo: false }) do |f| %>
  <p>
    <%= f.label :name, "Enter a genre" %><br/>
    <%= f.text_field :name %>
  </p>
  <p>
  <%= f.submit %>
</p>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">MovieCollectionManagementApp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Add Movie', new_movie_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
      <%= link_to 'Add a Genre', new_genre_path, class: 'nav-link' %>
    </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieCollection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  </head>

  <body>
  <% flash.each do |key, value| %>
    <div class="flash <%= key %>"><%= value %></div>
  <% end %>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  <%= render 'layouts/navigation' %>

    <%= yield %>
  </body>
</html>

app/views/movies/edit.html.erb
<h2>You are editing <%=  @movie.display_movie_director_realse_year(@movie) %> </h2>

<%= form_with(model: @movie, local: true, data: { turbo: false }) do |f| %>

<p>
<%= f.label :view_count, "Enter a views" %><br/>
<%= f.text_field :view_count , value: @movie.view_count %>
</p>

  <p>
    <%= f.submit %>
  </p>

  <% end %>

app/views/movies/index.html.erb
<h1>Welcome to the Movie Collection Management App!</h1>
<table class="table">
  <thead>
    <tr>
      <th>Movies</th>
      <th>Genres</th>
      <th>Views</th>
      <th>Edit</th>

    </tr>
  </thead>
  <tbody>
  <% @movies.each do |movie| %>
    <tr>
      <td><%= movie.display_movie_director_realse_year(movie) %></td>
      <td><%= "Genres: #{movie.display_genres(movie)}" %></td>
      <td>Views: <%= movie.view_count %> <%= "Most Viewed"  if movie.most_watched? %></td>
      <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
    </tr>
  <% end %>
</tbody>
   
</table>

app/views/movies/new.html.erb
<h1>Add a Movie</h1>
<% if @movie.errors.any? %>
  <h2>You got an error</h2>
  <ul>
    <% @movie.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with(model: @movie, local: true, data: { turbo: false }) do |f| %>
  <p>
    <%= f.label :title, "Title" %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
  <%= f.label :director, "Director" %><br/>
  <%= f.text_field :director %>
</p>

<p>
<%= f.label :release_year, "Release Year" %><br/>
<%= f.text_field :release_year %>
</p>

<h6>Genres:</h6>
<%= f.collection_check_boxes(:genre_ids, Genre.order(:name), :id, :name) %>

<p>
  <%= f.submit %>
</p>
<% end %>